package Constantes;

public class Constantes {


    public  static int GUI_BOUNDS_X=1980;
    public static int GUI_BOUNDS_Y=1040;
    public static int PUNTAJE_BOUNDS_PX=1400,PUNTAJE_BOUNDS_PY=33,PUNTAJE_BOUNDS_X=128,PUNTAJE_BOUNDS_Y=25;
    public static int PANEL_TIENDA_PX=100,PANEL_TIENDA_PY=0,PANEL_TIENDA_X=992,PANEL_TIENDA_Y=230;
    public static int BOTON1_PX=0;
    public static int BOTONES_PY=120,BOTONES_X=149,BOTONES_Y=120;
    public static int GRILLA_X1=150,GRILLA_X2=170,GRILLA_Y1=300,GRILLA_Y2=105;
    public static int COLUMNA_1=65,COLUMNA_2=170;
    public static int FILA_1=255,FILA_2=105;
    public static int ALIADOX=100,ALIADOY=120;
    public static int ENEMIGOS_PX=1800;
    public static int ENEMIGO_Y1=285,ENEMIGO_Y2=105,ENEMIGO_BOUNDS1=6;
    public static int TREINTA=22;


    public static void actualizar(int rx, int ry){
        GUI_BOUNDS_X=rx;
        GUI_BOUNDS_Y=ry;
        PUNTAJE_BOUNDS_PX=(PUNTAJE_BOUNDS_PX*GUI_BOUNDS_X)/1980;

        PUNTAJE_BOUNDS_PY=(PUNTAJE_BOUNDS_PY*GUI_BOUNDS_Y)/1040;

        PUNTAJE_BOUNDS_X=(PUNTAJE_BOUNDS_X*GUI_BOUNDS_X)/1980;

        PUNTAJE_BOUNDS_Y=(PUNTAJE_BOUNDS_Y*GUI_BOUNDS_Y)/1040;

        PANEL_TIENDA_PX=(PANEL_TIENDA_PX*GUI_BOUNDS_X)/1980;

        PANEL_TIENDA_PY=(PANEL_TIENDA_PY*GUI_BOUNDS_Y)/1040;//

        PANEL_TIENDA_Y=(PANEL_TIENDA_Y*GUI_BOUNDS_Y)/1040;

        BOTON1_PX=(BOTON1_PX*GUI_BOUNDS_X)/1980;

        BOTONES_PY=(BOTONES_PY*GUI_BOUNDS_Y)/1040;

        BOTONES_X=(BOTONES_X*GUI_BOUNDS_X)/1980;

        BOTONES_Y=(BOTONES_Y*GUI_BOUNDS_Y)/1040;

        GRILLA_X1=(GRILLA_X1*GUI_BOUNDS_X)/1980;

        GRILLA_Y1=(GRILLA_Y1*GUI_BOUNDS_Y)/1040;

        GRILLA_X2=(GRILLA_X2*GUI_BOUNDS_X)/1980;

        GRILLA_Y2=(GRILLA_Y2*GUI_BOUNDS_Y)/1040;//

        COLUMNA_1=(COLUMNA_1*GUI_BOUNDS_X)/1980;

        COLUMNA_2=(COLUMNA_2*GUI_BOUNDS_X)/1980;

        FILA_1=(FILA_1*GUI_BOUNDS_Y)/1040;

        FILA_2=(FILA_2*GUI_BOUNDS_Y)/1040;

        ALIADOX=(ALIADOX*GUI_BOUNDS_X)/1980;

        ALIADOY=(ALIADOY*GUI_BOUNDS_Y)/1040;

        ENEMIGOS_PX=((ENEMIGOS_PX*GUI_BOUNDS_X)/1980);

        ENEMIGO_Y1=(ENEMIGO_Y1*GUI_BOUNDS_Y)/1040;
        ENEMIGO_Y2=(ENEMIGO_Y2*GUI_BOUNDS_Y)/1040;

        ENEMIGO_BOUNDS1=(ENEMIGO_BOUNDS1*GUI_BOUNDS_Y)/1040;

        TREINTA=(TREINTA*GUI_BOUNDS_X)/1980;
    }


}
